version: "3"

services:
    database:
        image: mongo:${MONGO_TAG}
        restart: always
        container_name: blog-database
        ports:
            - ${MONGO_PORT}:27017
        networks:
            internal_network:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ./db:/data/db
            - ./config:/data/configdb
    api:
        restart: unless-stopped
        container_name: blog-api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        ports:
            - 48312:${NODE_PORT}
        environment:
            - MONGO_HOST=172.18.0.1
            - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
            - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
        networks:
            internal_network:
            app_network:

networks:
    app_network:
        external: true
    internal_network:
