name: CI

on:
    push:
    schedule:
        - cron: "0 21 * * 0"

env:
    CI: true
jobs:
    check-spelling:
        name: Check spelling
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: marshallku/actions/analyze/spell@master
    build:
        name: Build all packages and apps
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions-rust-lang/setup-rust-toolchain@v1
            - run: cargo build
    # sonarqube:
    #     name: Analyze with SonarQube
    #     runs-on: ubuntu-latest
    #     if: github.ref == 'refs/heads/master'
    #     steps:
    #         - uses: actions/checkout@v4
    #           with:
    #               fetch-depth: 0
    #         - uses: sonarsource/sonarqube-scan-action@v2
    #           env:
    #               SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #               SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    send-notification:
        needs: [check-spelling, build]
        if: ${{ failure() }}
        uses: marshallku/actions/.github/workflows/send-notification.yml@master
        with:
            failed: ${{ contains(join(needs.*.result, ','), 'failure') }}
            message: "CI job failed"
        secrets:
            url: ${{ secrets.DISCORD_WEBHOOK_URI }}
